config/routes.rb
Rails.application.routes.draw do
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get    'logout' => 'sessions#destroy'

  get 'links', to: 'offers#index', as: 'links'
  get 'offers/:secure_list_id/answers', param: :secure_list_id, to: 'answers#index', as: 'offer_answers'
  get 'offers/:secure_create_id/answers/new', param: :secure_create_id, to: 'answers#new', as: 'new_offer_answer'
  post 'offers/:secure_create_id/answers/new', param: :secure_create_id, to: 'answers#create', as: 'create_offer_answer'
  get 'ok', to: 'answers#ok', as: 'answer_ok'

  resources :users

  root 'sessions#new'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :offer
  before_create :randomize_id

  validates :a01, presence: true
  validates :a02, presence: true
  validates :a03, presence: true
  validates :a04, presence: true
  validates :a05, presence: true
  validates :a06, presence: true
  validates :a07, presence: true
  validates :a08, presence: true
  validates :a09, presence: true
  validates :a10, presence: true
  validates :a11, presence: true
  validates :a12, presence: true
  validates :a13, presence: true
  validates :a14, presence: true
  validates :comment, presence: true, length: { minimum: 3 }

  def self.como_aluno
    {
      :a01 => "Meus conhecimentos prévios para acompanhar o componente curricular são:",
      :a02 => "Minha aprendizagem neste componente curricular está sendo:",
      :a03 => "Minha motivação para freqüentar o componente curricular é:",
      :a04 => "Minha avaliação da turma (do componente curricular) quanto a empenho, dedicação e motivação neste componente curricular é:",
      :a05 => "Minha visão sobre o tempo que eu dedico para estudar este componente curricular é:",
      :a06 => "Em relação a outros componentes curriculares que você está cursando, avalie o nível de complexidade deste componente:",
    }
  end
  def self.sobre_professor
    {
      :a07 => "A motivação do professor para ministrar as aulas é:",
      :a08 => "O desenvolvimento dos conteúdos, quanto a clareza, objetividade e metodologia, é:",
      :a09 => "O conhecimento do professor, independente da didática, sobre o conteúdo ministrado é:",
      :a10 => "O planejamento das aulas, quanto a encadeamento de assuntos, exercícios é:",
      :a11 => "Os instrumentos de avaliação (provas, trabalhos, etc) e os critérios (peso, individual/em grupo, etc) são:",
      :a12 => "O relacionamento do professor com os alunos é:",
      :a13 => "O aproveitamento do tempo de aula pelo professor é:",
      :a14 => "Quanto à preocupação com a aprendizagem do aluno, a atuação do professor é:"
    }
  end
  def self.todas_perguntas
    self.como_aluno.merge self.sobre_professor
  end

  def self.resposta_pergunta
    bom_mal = (1..5).zip ["péssimo", "ruim", "regular", "bom", "excelente"]
    facil_dificil = (1..5).zip ["muito fácil", "fácil", "médio", 
                     "difícil", "muito difícil"]
    {
      :a01 => bom_mal,
      :a02 => bom_mal,
      :a03 => bom_mal,
      :a04 => bom_mal,
      :a05 => bom_mal,
      :a06 => facil_dificil,
      :a07 => bom_mal,
      :a08 => bom_mal,
      :a09 => bom_mal,
      :a10 => bom_mal,
      :a11 => bom_mal,
      :a12 => bom_mal,
      :a13 => bom_mal,
      :a14 => bom_mal
    }
  end

  def texto(cod)
    bom_mal = Hash[(1..5).zip ["péssimo", "ruim", "regular", "bom", "excelente"]]
    facil_dificil = Hash[(1..5).zip ["muito fácil", "fácil", "médio", "difícil", "muito difícil"]]

    if cod == :a06
      facil_dificil[send cod]
    else
      bom_mal[send cod]
    end
  end

  def to_param
    secure_id.to_s
  end

  private
  def randomize_id
    begin
      self.secure_id = SecureRandom.random_number(2**63)
    end while Answer.where(secure_id: self.secure_id).exists?
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  #before_action :set_offer
  before_action :set_answer, only: [:show, :edit, :update, :destroy]


  # GET /answers
  # GET /answers.json
  def index
    @offer = Offer.find_by(secure_list_id: params[:secure_list_id])
    @answers = @offer.answers

    @data = Answer.resposta_pergunta.keys.map { |k|
      @answers.map { |a| 
        [Answer.todas_perguntas[k], a.texto(k)]
      }
    }.flatten(1).group_by { |k,v| k }
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /ok
  def ok
  end

  # GET /answers/new
  def new
    @offer = Offer.find_by(secure_create_id: params[:secure_create_id])
    @answer = Answer.new(offer: @offer)
  end

  # POST /answers
  # POST /answers.json
  def create
    @offer = Offer.find_by(secure_create_id: params[:secure_create_id])
    @answer = @offer.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to answer_ok_path, notice: 'Sua resposta foi recebida.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_offer_list
    #  @offer = Offer.find_by(secure_id: params[:offer_id])
    #end
    def set_answer
      @answer = Answer.find_by(secure_id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:offer_id, :a01, :a02, :a03, :a04, :a05, :a06, :a07, :a08, :a09, :a10, :a11, :a12, :a13, :a14, :comment)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for([@offer, @answer], url: create_offer_answer_path(@offer.secure_create_id)) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2> Professor: </h2>
    <%= @offer.professor.name %>
    <h2> Disciplina: </h2>
    <%= @offer.course.name %>
    <h2> Turno: </h2>
    <%= @offer.turno %>
    <h2>Fase: </h2>
    <%= @offer.semester %>
  </div>

  <div class="field">
    <%= f.label :a01 %><br>
    <%= f.number_field :a01 %>
  </div>
  <div class="field">
    <%= f.label :a02 %><br>
    <%= f.number_field :a02 %>
  </div>
  <div class="field">
    <%= f.label :a03 %><br>
    <%= f.number_field :a03 %>
  </div>
  <div class="field">
    <%= f.label :a04 %><br>
    <%= f.number_field :a04 %>
  </div>
  <div class="field">
    <%= f.label :a05 %><br>
    <%= f.number_field :a05 %>
  </div>
  <div class="field">
    <%= f.label :a06 %><br>
    <%= f.number_field :a06 %>
  </div>
  <div class="field">
    <%= f.label :a07 %><br>
    <%= f.number_field :a07 %>
  </div>
  <div class="field">
    <%= f.label :a08 %><br>
    <%= f.number_field :a08 %>
  </div>
  <div class="field">
    <%= f.label :a09 %><br>
    <%= f.number_field :a09 %>
  </div>
  <div class="field">
    <%= f.label :a10 %><br>
    <%= f.number_field :a10 %>
  </div>
  <div class="field">
    <%= f.label :a11 %><br>
    <%= f.number_field :a11 %>
  </div>
  <div class="field">
    <%= f.label :a12 %><br>
    <%= f.number_field :a12 %>
  </div>
  <div class="field">
    <%= f.label :a13 %><br>
    <%= f.number_field :a13 %>
  </div>
  <div class="field">
    <%= f.label :a14 %><br>
    <%= f.number_field :a14 %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listagem de respostas para disciplina:
    <%= @offer.course.name %> - <%= @offer.turno %>
    (<%= @offer.professor.name %>)
</h1>

<% if @answers.count == 0 %>
  <h1 style="color:red;"> Ainda não foram enviadas respostas! </h1>
<% else %>

  <% @data.each do |q, as| %>
    <h2> <%= q %> </h2>
    <p> <%= teste(as) %> </p>
  <% end %>

  <h1> Comentários </h1>
    <ul>
      <% @answers.each do |answer| %>
        <li> <%= answer.comment %> </li>
      <% end %>
    </ul>

  <br>

<% end %>

app/views/answers/new.html.erb
<h1>
  Avaliação do Componente Curricular:
    <%= @offer.course.name %> - <%= @offer.turno %>
    (<%= @offer.professor.name %>)
</h1>

<%= form_for([@offer, @answer], url: create_offer_answer_path(@offer.secure_create_id))  do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2> Como Aluno: </h2>

  <% Answer.como_aluno.each do |k,t| %>
    <div class="field">
      <%= f.label t %><br>
      <% Answer.resposta_pergunta[k].each do |nr,txt| %>
        <%= f.radio_button k, nr %> 
        <%= f.label txt %> <br />
      <% end %>
    </div>
  <% end %>

  <h2>O professor do componente curricular:</h2>

  <% Answer.sobre_professor.each do |k,t| %>
    <div class="field">
      <%= f.label t %><br>
      <% Answer.resposta_pergunta[k].each do |nr,txt| %>
        <%= f.radio_button k, nr %> 
        <%= f.label txt %> <br />
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Críticas e sugestões:" %><br/>
    <font color=gray> Sua opinião é importante para o melhoramento da disciplina e crescimento do professor.</font>
    <br/>
    
    <%= f.text_area :comment, size: "60x10" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p> Obrigado por submeter sua avaliação </p>