config/routes.rb
Rails.application.routes.draw do
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get    'logout' => 'sessions#destroy'

  get 'links', to: 'offers#index', as: 'links'
  get 'offers/:secure_list_id/answers', param: :secure_list_id, to: 'answers#index', as: 'offer_answers'
  get 'offers/:secure_create_id/answers/new', param: :secure_create_id, to: 'answers#new', as: 'new_offer_answer'
  post 'offers/:secure_create_id/answers/new', param: :secure_create_id, to: 'answers#create', as: 'create_offer_answer'
  get 'ok', to: 'answers#ok', as: 'answer_ok'

  resources :users

  root 'sessions#new'

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :professor
  belongs_to :course
  has_many :answers
  before_create :randomize_id


  def self.create_by_names!(codigo, nome, professor, turno, fase, ativo)

    to_bool = {'S' =>  true, 'N' => false }
    from_turno = {'M'=> 1, 'N' => 2}

    c = Course.find_or_create_by!(code: codigo, name: nome)
    p = Professor.find_or_create_by!(name: professor)
    Offer.find_or_create_by!(
      professor: p, 
      course: c,
      semester: fase.to_i,
      shift: from_turno[turno],
      active: to_bool[ativo]
    )
  end


  def turno 
    to_turno = {1 => 'Matutino', 2 => 'Noturno'}
    to_turno[shift]

  end


  #def to_param
  #  secure_id.to_s
  #end


  private
  def randomize_id
    self.secure_create_id = SecureRandom.random_number(2**63)
    self.secure_list_id = SecureRandom.random_number(2**63)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  # GET /offers
  # GET /offers.json
  def index
    if logged_in?
    else
      redirect_to login_path
    end
    #redirect_to login_path
    @offers = Offer.all
  end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professor_id %><br>
    <%= f.text_field :professor_id %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing Offer</h1>

<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listagem de Disciplinas por fase</h1>

<table border="1px">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Professor</th>
      <th>Turno</th>
      <th>Respostas</th>
      <th>Número de Respostas</th>
      <th>Link para responder</th>
    </tr>
  </thead>

  <tbody>
    <% @offers.select { |o| o.active }.group_by { |o| o.semester }.sort_by { |s, os| s }.each do |s, offers| %>
      <tr> <th colspan="7"> Fase: <%= s %> </th> </tr>
      <% offers.sort_by { |o| o.course.code }.each do |offer| %>
        <tr>
          <td><%= offer.course.code %></td>
          <td><%= offer.course.name %></td>
          <td><%= offer.professor.name %></td>
          <td><%= offer.turno %></td>
          <td><%= link_to 'Respostas', offer_answers_path(offer.secure_list_id) %></td>
          <td><%= offer.answers.count %></td>
          <td><%= link_to 'New Answer', new_offer_answer_path(offer.secure_create_id) %> </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/offers/new.html.erb
<h1>New Offer</h1>

<%= render 'form' %>

<%= link_to 'Back', offers_path %>

app/views/offers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Professor:</strong>
  <%= @offer.professor %>
</p>

<p>
  <strong>Course:</strong>
  <%= @offer.course %>
</p>

<%= link_to 'Edit', edit_offer_path(@offer) %> |
<%= link_to 'Back', offers_path %>